<<<<<<< HEAD
# Site settings
title: DIFFversity
email: NOOB@diff.WTF
description: Speak in the pompatus of DIFF . . . Learn. Appreciate. UNDERSTAND.
twitter_username: DIFFversity
github_username:  DIFFwtf

# Build settings
markdown: kramdown
=======
theme: jekyll-theme-minimal
>>>>>>> 18acfbe3b009e56dfbd51df699520e05a06f154b
