# Site settings
title: DIFFversity
email: NOOB@diff.WTF
description: Speak in the pompatus of DIFF . . .  the WTF process or WORK THINK FLOW process is demanding and DIFFicult ... respecting DIFFerences is not about avoiding differences or arguments ... it is about WORKING with ideas, THINKING about differences, and working out the FLOW. So WTF is the fundamentally disruptive method of Learn. Appreciate. UNDERSTAND. ... ultimately, the WORK and THINKING must FLOW.
twitter_username: DIFFversity
github_username:  DIFFwtf

# Build settings
markdown: kramdown
