# Site settings
title: DIFFversity
email: NOOB@diff.WTF
description: Speak in the pompatus of DIFF . . .  workTHINKflow process is demanding and DIFFicult; respecting DIFFerences is not about avoiding differences; it is about THINKING and what is different and WHY. Achieving FLOW is fundamentally disruptive; so first we must Learn. Appreciate. UNDERSTAND. ... but ultimately, the WORK of THINKING must FLOW.
twitter_username: DIFFversity
github_username:  DIFFwtf

# Build settings
markdown: kramdown
